name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main # This workflow runs when you push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Runs on the latest Ubuntu virtual machine

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3 # Fetches the code from GitHub repository

      # Step 2: Set up Node.js (required for React)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Set the Node.js version to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install # This will install all the required dependencies (e.g., react-scripts)

      # Step 4: Build the React app
      - name: Build React app
        run: npm run build # This creates the optimized production build in the `build/` folder

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        run: |
          # Write the private SSH key from GitHub Secrets to a file
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_ssh_key.pem
          chmod 600 aws_ssh_key.pem  # Set proper file permissions for the private key
          eval "$(ssh-agent -s)"     # Start SSH agent
          ssh-add aws_ssh_key.pem    # Add SSH key to the agent

          # SSH into the EC2 instance and deploy the React app
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Navigate to the workspace folder
            cd /home/ubuntu/workspace

            # Check if the project directory exists. If not, clone the repository.
            if [ ! -d "/home/ubuntu/workspace/shope-ease/.git" ]; then
              git clone https://github.com/ARVishnu/shope-ease.git shope-ease
            else
              # If the repo already exists, pull the latest changes
              cd /home/ubuntu/workspace/shope-ease
              git pull origin main
            fi

            # Navigate to the project directory
            cd /home/ubuntu/workspace/shope-ease

            # Install dependencies (if there are any new dependencies)
            npm install

            # Build the React app for production
            npm run build

            # Ensure nginx is installed and restart it
            if ! which nginx > /dev/null; then
              sudo apt update
              sudo apt install -y nginx
            fi

            # Restart Nginx to serve the new build
            sudo systemctl restart nginx
          EOF
