# name: Deploy React App to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"

#       - name: Install dependencies
#         run: npm install

#       - name: Build React app
#         run: npm run build

#       - name: Deploy to EC2
#         run: |
#           # Write the private SSH key from GitHub Secrets to a file
#           echo "${{ secrets.AWS_SSH_KEY }}" > aws_ssh_key.pem
#           chmod 600 aws_ssh_key.pem  # Set proper file permissions for the private key
#           eval "$(ssh-agent -s)"     # Start SSH agent
#           ssh-add aws_ssh_key.pem    # Add SSH key to the agent

#           # SSH into the EC2 instance and deploy the React app
#           ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
#             cd /home/ubuntu/workspace

#             if [ ! -d "/home/ubuntu/workspace/shope-ease/.git" ]; then
#               git clone https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/ARVishnu/shope-ease.git shope-ease
#             else
#               cd /home/ubuntu/workspace/shope-ease
#               git pull https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/ARVishnu/shope-ease.git main
#             fi

#             cd /home/ubuntu/workspace/shope-ease
#             npm install
#             npm run build

#             if [ ! -d "./dist" ]; then
#               echo "Build directory not found. Exiting."
#               exit 1
#             fi

#             sudo npm install -g http-server
#             PID=$(sudo lsof -t -i:80)
#             if [ -n "$PID" ]; then
#               sudo kill -9 $PID
#             fi

#             sudo nohup http-server ./dist -p 80 &
#             disown
#             sleep 5
#             echo "Deployment successful!"
#             exit
#           EOF
