name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Create Docker image and Deploy to EC2
        run: |
          # Write the private SSH key from GitHub Secrets to a file
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_ssh_key.pem
          chmod 600 aws_ssh_key.pem  # Set proper file permissions for the private key
          eval "$(ssh-agent -s)"     # Start SSH agent
          ssh-add aws_ssh_key.pem    # Add SSH key to the agent

          # SSH into the EC2 instance and deploy the Dockerized React app
          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Navigate to the workspace
            cd /home/ubuntu/workspace

            # Clone the repo if it doesn't exist, or pull the latest changes
            if [ ! -d "/home/ubuntu/workspace/shope-ease/.git" ]; then
              git clone https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/ARVishnu/shope-ease.git shope-ease
            else
              cd /home/ubuntu/workspace/shope-ease
              git pull https://${{ secrets.USERNAME }}:${{ secrets.PAT }}@github.com/ARVishnu/shope-ease.git main
            fi

            cd /home/ubuntu/workspace/shope-ease

            # Build the React app
            npm install
            npm run build

            # Create a Dockerfile if it doesn't already exist
            if [ ! -f "Dockerfile" ]; then
              cat << 'EOF2' > Dockerfile
              # Use an official Node.js image as the build stage
              FROM node:18-alpine as build

              # Set working directory
              WORKDIR /app

              # Copy package files and install dependencies
              COPY package*.json ./
              RUN npm install

              # Copy source code and build the app
              COPY . .
              RUN npm run build

              # Use Nginx for the final stage to serve static files
              FROM nginx:alpine
              COPY --from=build /app/build /usr/share/nginx/html

              # Expose port 80
              EXPOSE 80
              CMD ["nginx", "-g", "daemon off;"]
              EOF2
            fi

            # Build the Docker image
            sudo docker build -t react-app .

            # Stop and remove any existing container
            sudo docker ps -q --filter "name=react-app" | xargs -r sudo docker stop
            sudo docker ps -a -q --filter "name=react-app" | xargs -r sudo docker rm

            # Run the Docker container
            sudo docker run -d -p 80:80 --name react-app react-app

            # Clean up
            sudo docker system prune -f

            echo "Deployment successful!"
            exit
          EOF
