name: Deploy React App to EC2 with Docker and Nginx

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          # Build Docker image for the React app with Nginx
          docker build -t my-react-app .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push my-react-app

      - name: SSH into EC2 and deploy the app
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_ssh_key.pem
          chmod 600 aws_ssh_key.pem
          eval "$(ssh-agent -s)"
          ssh-add aws_ssh_key.pem

          ssh -o ServerAliveInterval=60 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            # Navigate to the workspace directory
            cd /home/ubuntu/workspace

            # Clone or update the repository
            if [ ! -d "/home/ubuntu/workspace/shope-ease/.git" ]; then
              git clone https://github.com/ARVishnu/shope-ease.git shope-ease
            else
              cd /home/ubuntu/workspace/shope-ease
              git pull origin main  # Pull the latest changes from the public repo
            fi

            # Navigate to the project folder and build the React app
            cd /home/ubuntu/workspace/shope-ease
            npm install
            npm run build

            # Check if dist folder exists
            if [ ! -d "./dist" ]; then
              echo "Build directory not found. Exiting."
              exit 1
            fi

            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker could not be found. Installing Docker..."
              sudo apt-get update
              sudo apt-get install -y docker.io
            fi

            # Pull the Docker image
            docker pull my-react-app

            # Stop and remove any running container
            docker stop react-app-container || true
            docker rm react-app-container || true

            # Run the React app inside a Docker container with Nginx
            docker run -d --name react-app-container -p 80:80 vishnuenest/my-react-app:latest

            # Restart Nginx to ensure it's serving the app
            sudo systemctl restart nginx

            echo "Deployment successful!"
            exit
          EOF
